CREATE TABLE MEMBER (
	ID	        	VARCHAR2(30)		NOT NULL,
	PW	          VARCHAR2(100)		NOT NULL,
	NAME	        VARCHAR2(20)		NOT NULL,
	EMAIL	        VARCHAR2(100)		NOT NULL,
	PHONE         VARCHAR2(30)		NOT NULL,
  ENABLED	    	NUMBER(1)     	DEFAULT 0 CHECK (ENABLED  IN (0,1)) NOT NULL,
  ROLENAME			VARCHAR2(20)		DEFAULT 'ROLE_USER' CHECK (ROLENAME IN ('ROLE_USER', 'ROLE_ADMIN','ROLE_EMP')) NOT NULL
);