CREATE TABLE MEMBER (
	USER_ID	        VARCHAR2(30)		PRIMARY KEY,
	USER_PW	        VARCHAR2(100)		NOT NULL,
	USER_NAME	    VARCHAR2(20)		NOT NULL,
	EMAIL	             VARCHAR2(100)		NOT NULL,
	PHONE                VARCHAR2(30)		NOT NULL,
    ENABLED	          NUMBER(1)            DEFAULT 0 CHECK (ENABLED  IN (0,1)) NOT NULL,
    ROLENAME	      VARCHAR2(20)	    DEFAULT 'ROLE_USER' CHECK (ROLENAME IN ('ROLE_USER', 'ROLE_ADMIN','ROLE_EMP')) NOT NULL,
    USER_NUM        NUMBER              NOT NULL
);

CREATE TABLE BOARD (
    BOARDNUM    NUMBER        PRIMARY KEY,
    TITLE    VARCHAR2(300)        NOT NULL,
    CONTENT    VARCHAR2(4000)        NOT NULL,
    VIEW_COUNT    NUMBER    DEFAULT 0    NOT NULL,
    INPUT_DATE    DATE    DEFAULT SYSDATE,
    USER_ID    VARCHAR2(30)  REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    BOARDTYPE   VARCHAR2(100)   NOT NULL,
    ORIGINALFILE    VARCHAR2(1000),
    SAVEDFILE    VARCHAR2(1000)
);

CREATE TABLE REPLY (
    REPLYNUM    NUMBER        PRIMARY KEY,
    REPLYTEXT    VARCHAR2(1000)        NOT NULL,
    BOARDNUM    NUMBER        REFERENCES BOARD(BOARDNUM) ON DELETE CASCADE,
    USER_ID    VARCHAR2(30)  REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    INPUT_DATE    DATE    DEFAULT SYSDATE
);

CREATE TABLE  BUSINESS (
    BUSINESS_NUM NUMBER PRIMARY KEY,
    BUSINESS_NAME    VARCHAR2(300)        NOT NULL,
    BUSINESS_ADDRESS    VARCHAR2(500)        NOT NULL,
    TOTAL_ROOM    NUMBER        NOT NULL,
    USER_ID    VARCHAR2(30)  REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    PHONE   VARCHAR2(30)
);

CREATE SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE BOARD_SEQ;
CREATE SEQUENCE REPLY_SEQ;

DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE REPLY;
DROP TABLE member CASCADE CONSTRAINTS;
DROP TABLE BUSINESS;

ALTER TABLE BUSINESS ADD PHONE VARCHAR2(30);
commit;
