CREATE TABLE MEMBER (
	USER_ID	        VARCHAR2(30)		PRIMARY KEY,
	USER_PW	        VARCHAR2(100)		NOT NULL,
	USER_NAME	    VARCHAR2(20)		NOT NULL,
	EMAIL	             VARCHAR2(100)		NOT NULL,
	PHONE                VARCHAR2(30)		NOT NULL,
    ENABLED	          NUMBER(1)            DEFAULT 0 CHECK (ENABLED  IN (0,1)) NOT NULL,
    ROLENAME	      VARCHAR2(20)	    DEFAULT 'ROLE_USER' CHECK (ROLENAME IN ('ROLE_USER', 'ROLE_ADMIN','ROLE_EMP')) NOT NULL
);

CREATE TABLE BOARD (
    BOARDNUM    NUMBER        PRIMARY KEY,
    TITLE    VARCHAR2(300)        NOT NULL,
    CONTENT    VARCHAR2(4000)        NOT NULL,
    VIEW_COUNT    NUMBER    DEFAULT 0    NOT NULL,
    INPUT_DATE    DATE    DEFAULT SYSDATE,
    USER_ID    VARCHAR2(30)  REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE REPLY (
    REPLYNUM    NUMBER        PRIMARY KEY,
    REPLYTEXT    VARCHAR2(1000)        NOT NULL,
    BOARDNUM    NUMBER        REFERENCES BOARD(BOARDNUM) ON DELETE CASCADE,
    USER_ID    VARCHAR2(30)  REFERENCES MEMBER(USER_ID) ON DELETE CASCADE,
    INPUT_DATE    DATE    DEFAULT SYSDATE
);

CREATE TABLE  BUSINESS (
    BUSINESS_NUM NUMBER PRIMARY KEY,
    BUSINESS_NAME    VARCHAR2(300)        NOT NULL,
    BUSINESS_ADDRESS    VARCHAR2(500)        NOT NULL,
    TOTAL_ROOM    NUMBER        NOT NULL,
    USER_ID    VARCHAR2(30)  REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
);


CREATE TABLE COMPLAIN_BOARD (
    BOARDNUM    NUMBER         PRIMARY KEY,
    TITLE    VARCHAR2(300)        NOT NULL,
    CONTENT    VARCHAR2(4000)        NOT NULL,
    INPUT_DATE    DATE    DEFAULT SYSDATE,
    CHECKED NUMBER(1) DEFAULT 0 NOT NULL,
    USER_ID    VARCHAR2(30)  REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE ANNOUNCEMENT (
    BOARDNUM    NUMBER         PRIMARY KEY,
    TITLE    VARCHAR2(300)        NOT NULL,
    CONTENT    VARCHAR2(4000)        NOT NULL,
    INPUT_DATE    DATE    DEFAULT SYSDATE,
    WRITER   VARCHAR2(30) DEFAULT '包府磊' 
);


CREATE TABLE COMPLAIN_REPLY (
    REPLYNUM    NUMBER        PRIMARY KEY,
    BOARDNUM   NUMBER REFERENCES COMPLAIN_BOARD(BOARDNUM) ON DELETE CASCADE,
    REPLYTEXT   VARCHAR2(1000)        NOT NULL,
    WRITER   VARCHAR2(30) DEFAULT '包府磊',
    INPUT_DATE   DATE    DEFAULT SYSDATE
);

commit;

CREATE SEQUENCE BOARD_SEQ;
CREATE SEQUENCE REPLY_SEQ;
CREATE SEQUENCE COMPLAIN_BOARD_SEQ;
CREATE SEQUENCE COMPLAIN_REPLY_SEQ;
CREATE SEQUENCE ANNOUNCEMENT_SEQ;